#!/usr/local/bin/python
""" 
   Program that shows the program on the right and its abstract syntax tree (ast) on the left.
"""
from __future__ import print_function

import argparse
from ast_viewer.controllers.shell import AstTransformInterpreter

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="AST Transform interpreter")
    parser.add_argument(
        '-i', '--interactive', help='interactive mode, allows direct communication with device', action="store_true"
    )
    parser.add_argument('-f', '--file', help='path to python source file')
    parser.add_argument('-v', '--verbose', help='show more debug than you like', action="store_true")

    args = parser.parse_args()

    interpreter = AstTransformInterpreter(args.file, verbose=False)

    if args.interactive:
        interpreter.interactive_mode()
    else:
        parser.print_usage()
